### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Alvin-LB** [Alvin-LB/NameTagChanger#2]
- [x] ~~Fix getUUIDs() method not being available in 1.8.8-1.9.4 (maybe further too)~~ Actually, just use newer ProtocolLib versions
- [x] Fix EnumGamemode being a subclass of WorldSettings in 1.8.8-1.9.4
- [ ] Fix position fields being ints in PacketPlayOutNamedEntitySpawn, breaking the PL implementation (1.8.8 and lower)
